export const knittingTerms = [
    { abbreviation: "Alt", english: "Alternate", norwegian: "Annenhver" },
    { abbreviation: "Approx", english: "Approximately", norwegian: "Omtrent" },
    { abbreviation: "-", english: "Backstitch", norwegian: "Attersting" },
    { abbreviation: "Beg", english: "Begin / Beginning", norwegian: "Begynn / Begynnelse" },
    { abbreviation: "Bet", english: "Between", norwegian: "Mellom" },
    { abbreviation: "BO", english: "Bind off", norwegian: "Fell av" },
    { abbreviation: "-", english: "Body", norwegian: "Bol" },
    { abbreviation: "CC", english: "Contrast Color", norwegian: "Kontrastfarge" },
    { abbreviation: "-", english: "Circular needle", norwegian: "Rundpinne" },
    { abbreviation: "Cn", english: "Cable needle", norwegian: "Flettepinne" },
    { abbreviation: "CO", english: "Cast on", norwegian: "Legg opp" },
    { abbreviation: "-", english: "Collar", norwegian: "Krage" },
    { abbreviation: "Cont", english: "Continue", norwegian: "Fortsett" },
    { abbreviation: "Dec", english: "Decrease", norwegian: "Ta inn / Fell av" },
    { abbreviation: "Dpn", english: "Double pointed needle", norwegian: "Strømpepinne" },
    { abbreviation: "-", english: "Edge", norwegian: "Kant" },
    { abbreviation: "-", english: "Edge Stitch", norwegian: "Kantmaske" },
    { abbreviation: "-", english: "Eyelet pattern", norwegian: "Hullmønster" },
    { abbreviation: "Foll", english: "Following", norwegian: "Følgende, neste" },
    { abbreviation: "fl", english: "Front loop of stitch", norwegian: "Forreste maskeledd" },
    { abbreviation: "g st", english: "Garter Stitch", norwegian: "Rettstrikk" },
    { abbreviation: "-", english: "Gauge", norwegian: "Strikkefasthet" },
    { abbreviation: "-", english: "Hem", norwegian: "Nederkant" },
    { abbreviation: "In(s)", english: "Inch(es)", norwegian: "2,54 cm" },
    { abbreviation: "Inc", english: "Increase", norwegian: "Legg ut, øk" },
    { abbreviation: "-", english: "Into back of stitch", norwegian: "Vridd" },
    { abbreviation: "K, k", english: "Knit", norwegian: "Strikk rett / Rettstrikk" },
    { abbreviation: "k1p1", english: "Knit one, purl one", norwegian: "1 rett, 1 vrang" },
    { abbreviation: "ktog", english: "Knit together", norwegian: "Strikk sammen" },
    { abbreviation: "k2tog", english: "Knit 2 together", norwegian: "Strikk to masker sammen" },
    { abbreviation: "LH", english: "Left hand", norwegian: "Venstre" },
    { abbreviation: "-", english: "Loop", norwegian: "Løkke" },
    { abbreviation: "lps", english: "Loops", norwegian: "Løkker" },
    { abbreviation: "-", english: "Loop stitch", norwegian: "Løkkemaske" },
    { abbreviation: "M1", english: "Make one", norwegian: "Øk 1 maske" },
    { abbreviation: "-", english: "Making up", norwegian: "Montering" },
    { abbreviation: "MC", english: "Main color", norwegian: "Hovedfarge" },
    { abbreviation: "Meas", english: "Measures", norwegian: "Måler" },
    { abbreviation: "-", english: "Moss stitch", norwegian: "Perlestrikk" },
    { abbreviation: "-", english: "Neckband", norwegian: "Halskant" },
    { abbreviation: "ndl(s)", english: "Needle(s)", norwegian: "Pinne(r)" },
    { abbreviation: "P, p", english: "Purl", norwegian: "Strikk vrangt / Vrangstrikk" },
    { abbreviation: "p2sso", english: "Pass 2 slipped stitches over", norwegian: "Trekk 2 løse masker over" },
    { abbreviation: "p2tog", english: "Purl 2 stitches together", norwegian: "Strikke to masker sammen vrangt" },
    { abbreviation: "Pat, patt", english: "Pattern", norwegian: "Oppskrift, mønster" },
    { abbreviation: "pm", english: "Place marker", norwegian: "Plasser maskemarkør" },
    { abbreviation: "pr", english: "Previous row", norwegian: "Forrige pinne" },
    { abbreviation: "Psso", english: "Pass slipped stitch over", norwegian: "Trekk den løse masken over" },
    { abbreviation: "R", english: "Row", norwegian: "Pinne" },
    { abbreviation: "Rem", english: "Remaining", norwegian: "Gjenværende, resterende" },
    { abbreviation: "Rep", english: "Repeat", norwegian: "Gjenta, repeter" },
    { abbreviation: "Rev", english: "Reverse", norwegian: "Omvendt, motsatt" },
    { abbreviation: "Rev stst", english: "Reverse stocking stitch", norwegian: "Omvendt glattstrikk" },
    { abbreviation: "RH", english: "Right hand", norwegian: "Høyre" },
    { abbreviation: "Rib", english: "Ribbed border", norwegian: "Vrangbord" },
    { abbreviation: "-", english: "Rounds", norwegian: "Omganger" },
    { abbreviation: "-", english: "Row of eyelet holes", norwegian: "Hullrad" },
    { abbreviation: "RS", english: "Right side", norwegian: "Rettsiden / Retten" },
    { abbreviation: "-", english: "Seam", norwegian: "Søm" },
    { abbreviation: "-", english: "Seed stitch", norwegian: "Perlestrikk" },
    { abbreviation: "sk", english: "Skip", norwegian: "Hopp over" },
    { abbreviation: "sl1", english: "Slip one stitch", norwegian: "Ta 1 maske løst av" },
    { abbreviation: "-", english: "Slip stitch", norwegian: "Kjedemaske / Luftmaske" },
    { abbreviation: "ssk", english: "slip slip knit", norwegian: "Ta to masker løs av hver for seg, strikk dem rett sammen." },
    { abbreviation: "st(s)", english: "Stitches", norwegian: "Masker" },
    { abbreviation: "st st", english: "Stocking stitch", norwegian: "Glattstrikk" },
    { abbreviation: "tbl", english: "Through back of loop", norwegian: "Gjennom bakre ledd av masken" },
    { abbreviation: "-", english: "Tension", norwegian: "Strikkefasthet" },
    { abbreviation: "tog", english: "Together", norwegian: "Sammen" },
    { abbreviation: "-", english: "Yarn", norwegian: "Garn" },
    { abbreviation: "WS", english: "Wrong side", norwegian: "Vrangsiden, vrangen" },
    { abbreviation: "yb", english: "Yarn back", norwegian: "Garnet bak" },
    { abbreviation: "yfwd/yf", english: "Yarn forward", norwegian: "Kast" },
    { abbreviation: "yo(n)", english: "Yarn over needle", norwegian: "Kast" },
    { abbreviation: "-", english: "Yoke", norwegian: "Rundt bærestykke" },
    { abbreviation: "yrn", english: "Yarn round needle", norwegian: "Kast" }
  ];